services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    container_name: chista_web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/web/php.ini:/usr/local/etc/php/php.ini
      - ./docker/web/apache.conf:/etc/apache2/sites-available/000-default.conf
    environment:
      - PHP_IDE_CONFIG=serverName=chista
    # Use extra_hosts to access local MySQL
    extra_hosts:
      - "host.docker.internal:host-gateway" 