version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: chista_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./public:/var/www/html/public
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - chista_network

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: chista_php
    volumes:
      - .:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql
    networks:
      - chista_network
    environment:
      - PHP_IDE_CONFIG=serverName=chista

  mysql:
    image: mysql:8.0
    container_name: chista_mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/schemas:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root_password}
      MYSQL_DATABASE: ${DB_NAME:-chista}
      MYSQL_USER: ${DB_USER:-chista_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-chista_password}
    networks:
      - chista_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: chista_phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: ${DB_USER:-chista_user}
      PMA_PASSWORD: ${DB_PASSWORD:-chista_password}
    depends_on:
      - mysql
    networks:
      - chista_network

volumes:
  mysql_data:
    driver: local

networks:
  chista_network:
    driver: bridge 